const VERSION_SNAPSHOT_INTERVAL_MS = 5 * 60 * 1000;
const DEFAULT_VERSION_LIMIT = 20;
const MAX_VERSION_LIMIT = 50;
const DEFAULT_ACTIVITY_LIMIT = 20;
const MAX_ACTIVITY_LIMIT = 50;

export {
  DEFAULT_ACTIVITY_LIMIT,
  DEFAULT_VERSION_LIMIT,
  MAX_ACTIVITY_LIMIT,
  MAX_VERSION_LIMIT,
  VERSION_SNAPSHOT_INTERVAL_MS,
};
